### ISSUE TITLE
Export to OBJ?

### ISSUE THREAD

**Issue by srfoster** [jeapostrophe/pict3d#20]
If I wanted to create something in pict3d and export it to an obj file, would that be possible?

I'm guessing that this isn't currently supported; so more specifically: What's the best way for me to access to the underlying vertex information after constructing a pict3d object/scene?

**Comment by jeapostrophe** [comment]
I think you basically want to take the pict3d scene and run `scene-map-shapes` on it such that your mapping function records the shape polygons. Another thing you could look at it is look at the `send-vertex-data` function and dump that data out. If you implement such a thing, I am happy to merge it, but would not otherwise implement it.

**Comment by srfoster** [comment]
Awesome.  Thanks!
